### ISSUE TITLE
handler function path is not copied correctly when functions are in subfolder

### ISSUE THREAD

**Issue by theburningmonk** [SAPessi/serverless-sam#13]
eg. I have functions inside a `functions` folder:
- functions
     - get-index.js
     - get-restaurants.js

and setup accordingly in the `serverless.yml`, but in the exported `template.yml` the `Handler` paths do not include the `functions` folder, which causes `sam local invoke` to fail.

**Comment by sapessi** [comment]
I've committed a fix. If you can, try and install 0.0.2 from this github repo in your serverless app and run the export again, it should maintain the the paths.

**Comment by theburningmonk** [comment]
just downloaded and tried 0.0.2 and the path is still not copied, ps. I'm using sls v1.22.0

**Comment by sapessi** [comment]
just to make sure, you are installing the plugin in the serverless folder - for example on my desktop, using from the path of a serverless application, I run the following: `npm install --prefix . /Users/username/workspace/serverless-sam/`

**Comment by theburningmonk** [comment]
i'm installing the plugin as a dev dependency in the project, so it'll  be `.../path/to/project/repo/node_modules/serverless-sam`

**Comment by sapessi** [comment]
The 0.0.2 with the latest fixes is not yet pushed to npm. You'd have to clone this repo in the node_modules folder to test the changes.

**Comment by sapessi** [comment]
Hey @theburningmonk , to make life easier, I've just published a `0.0.3` of the plugin to npm, you should be able to install from there (or upgrade)
